### ISSUE TITLE
Documentation: Fix wrong links in the README file

### ISSUE THREAD

**Issue by ilankri** [besport/ocaml-cordova-plugin-firebase#4]
Since this is a binding for https://github.com/chemerisuk/cordova-plugin-firebase-analytics, the links in the README file should point to this repository instead of https://github.com/arnesson/cordova-plugin-firebase.

**Comment by Thibaut-Gudin** [comment]
Since the name of the library is "ocaml-cordova-plugin-firebase", I feel obligated to indicates the reference to the "firebase" APi if someone wants to upgrade the repository later. I haven't notice when I created it but I should have name this library "ocaml-cordova-plugin-firebase-analytics".

But I will add the reference to it in an upcomming Pull request were I will also fix some problem with the ".mli" file in an 2.0 version (naming confusion).

**Comment by Thibaut-Gudin** [comment]
https://github.com/besport/ocaml-cordova-plugin-firebase/pull/5
